name: cc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,18,02 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Install dependencies
        run: pip install pytz
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Install dependencies
        run: pip install Beautifulsoup4 requests 
      - name: Install dependencies
        run: pip3 install translate
        
      - name: Run iptv-zb
        run: python ${{ github.workspace }}/iptv_udp.py

      - name: Run txt_m3u
        run: python ${{ github.workspace }}/txt_m3u.py 
         
      - name: 提交更改
        run: |
          git config --local user.email "lucheng7996@163.com"
          git config --local user.name "lucheng7996"
          git reset --hard origin/main
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
